### PR TITLE
Change output to log CIRCSTORE-26

### PR DESCRIPTION
**Pull request by marcjohnson-kint**
Change code which outputs messages to standard out to use a logger instead, in order to resolve vulnerabilities reported by SonarQube

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
Thanks @julianladisch for spotting this. I have created a class which describes this behaviour, so it is harder for me to forget or be inconsistent next time. 

Thoughts welcome (I could figure out how to reply directly to your changes required comment)

**Comment by marcjohnson-kint** [comment]
@julianladisch Sure, the LogWriter was added for my convenience (as a memory aid as much as anything else), I wasn't aware of RMB-211 at the time. This can be converted to use it when it is ready.

**Comment by julianladisch** [comment]
@marcjohnson-kint Whatever you like.

**Comment by marcjohnson-kint** [comment]
@julianladisch I have raised a fresh pull request with the previous branch

**Pull request closed without merging**
