### PR TITLE
CIRCSTORE-247 - Request log actions

### PR DESCRIPTION
**Pull request by siarhei-charniak**
[CIRCSTORE-247](https://issues.folio.org/browse/CIRCSTORE-247) - Request log actions

### CODE REVIEW

**Comment by bohdan-suprun** [comment]
Hi @marcjohnson-kint, I'm approving it because @siarhei-charniak told me that this is a release blocker so he has created a tech debt https://issues.folio.org/browse/CIRCSTORE-259 to improve coverage up to 80%.

**Comment by marcjohnson-kint** [comment]
> Hi @marcjohnson-kint, I'm approving it because @siarhei-charniak told me that this is a release blocker so he has created a tech debt https://issues.folio.org/browse/CIRCSTORE-259 to improve coverage up to 80%.
> 
> Is it fine with you?

The Core Functional team don't need to approve this, unless there is no one in the Firebird team to conduct a review. Is that the case?

**Comment by bohdan-suprun** [comment]
> > Hi @marcjohnson-kint, I'm approving it because @siarhei-charniak told me that this is a release blocker so he has created a tech debt https://issues.folio.org/browse/CIRCSTORE-259 to improve coverage up to 80%.
> > Is it fine with you?
> 
> The Core Functional team don't need to approve this, unless there is no one in the Firebird team to conduct a review. Is that the case?

@marcjohnson-kint, I assume yes.

**Comment by marcjohnson-kint** [comment]
> > > Hi @marcjohnson-kint, I'm approving it because @siarhei-charniak told me that this is a release blocker so he has created a tech debt https://issues.folio.org/browse/CIRCSTORE-259 to improve coverage up to 80%.
> > > Is it fine with you?
> > 
> > 
> > The Core Functional team don't need to approve this, unless there is no one in the Firebird team to conduct a review. Is that the case?
> 
> @marcjohnson-kint, I assume yes.

@siarhei-charniak please an you confirm that you need an expediting review because there is no reviewer from Firebird. (I don't know if reviews are mandatory in this repository)

**Comment by siarhei-charniak** [comment]
> > > > Hi @marcjohnson-kint, I'm approving it because @siarhei-charniak told me that this is a release blocker so he has created a tech debt https://issues.folio.org/browse/CIRCSTORE-259 to improve coverage up to 80%.
> > > > Is it fine with you?
> > > 
> > > 
> > > The Core Functional team don't need to approve this, unless there is no one in the Firebird team to conduct a review. Is that the case?
> > 
> > 
> > @marcjohnson-kint, I assume yes.
> 
> @siarhei-charniak please an you confirm that you need an expediting review because there is no reviewer from Firebird. (I don't know if reviews are mandatory in this repository)

@bohdan-suprun, at the moment nobody from the Firebird team can conduct a review due to the sick leave

**Review by bohdan-suprun — APPROVED** [review]

**Pull request merged**
