### PR TITLE
CIRCSTORE-355: Allow compile and build on ARM64 machine

### PR DESCRIPTION
**Pull request by hjiebsco**
Update `testcontainer` and `confluentinc/cp-kafka` so it can build on arm64 machine.

[CIRCSTORE-355](https://issues.folio.org/browse/CIRCSTORE-355)

### CODE REVIEW

**Comment by OleksandrVidinieiev** [comment]
Hi @hjiebsco. Is there a Jira ticket for this issue?

**Comment by hjiebsco** [comment]
> Hi @hjiebsco. Is there a Jira ticket for this issue?

No. It is just a minor issue when we try to build the module on arm machine.

**Comment by OleksandrVidinieiev** [comment]
> No. It is just a minor issue when we try to build the module on arm machine.

Since we want to merge this into master, this fix is going to be released at some point. During the release we usually spend quite some time trying to match git history with corresponding Jira tickets to make sure the two are in sync. And ecountering commits not linked to a ticket usually is frustrating, since you can never be sure if that was intended or the author just forgot to link their PR to the ticket. Also, such changes look awkward in release changelog. So please create a Jira ticket for this welcome improvement and link it to the PR.

**Comment by hjiebsco** [comment]
> > No. It is just a minor issue when we try to build the module on arm machine.
> 
> Since we want to merge this into master, this fix is going to be released at some point. During the release we usually spend quite some time trying to match git history with corresponding Jira tickets to make sure the two are in sync. And encountering commits not linked to a ticket usually is frustrating, since you can never be sure if that was intended or the author just forgot to link their PR to the ticket. Also, such changes look awkward in release changelog. So please create a Jira ticket for this welcome improvement and link it to the PR.

Created https://issues.folio.org/browse/CIRCSTORE-355 Allow compile and build on ARM64 machine

**Comment by OleksandrVidinieiev** [comment]
> Created https://issues.folio.org/browse/CIRCSTORE-355 Allow compile and build on ARM64 machine

Great, thank you!

**Review by OleksandrVidinieiev — APPROVED** [review]

**Pull request merged**
